from p4utils.utils.topology import Topology
from p4utils.utils.sswitch_API import *
from crc import Crc
import socket, struct, pickle, os
max_val = 4294967295
crc32_polinomials = [0x04C11DB7, 0xEDB88320, 0xDB710641, 0x82608EDB, 0x741B8CD7, 0xEB31D82E,
                     0xD663B05, 0xBA0DC66B, 0x32583499, 0x992C1A4C, 0x32583499, 0x992C1A4C]


class EController(object):

    def __init__(self, sw_name, set_hash):

        self.topo = Topology(db="topology.db")
        self.sw_name = sw_name
        self.set_hash = set_hash
        self.thrift_port = self.topo.get_thrift_port(sw_name)
        self.controller = SimpleSwitchAPI(self.thrift_port)

        self.custom_calcs = self.controller.get_custom_crc_calcs()
        self.register_num = 4 #len(self.custom_calcs)
        print "register_num is {}.".format(self.register_num)

        self.init()
        self.registers = []

    def init(self):
        if self.set_hash:
            self.set_crc_custom_hashes()
        self.create_hashes()

    def set_forwarding(self):
        self.controller.table_add("forwarding", "set_egress_port", ['1'], ['2'])
        self.controller.table_add("forwarding", "set_egress_port", ['2'], ['1'])

    def reset_registers(self):
        len_ = len(self.controller.register_read("G"))
        for i in range(len_):
            self.controller.register_write("G", i, max_val)
        for j in range(1, self.register_num):
            for i in range(len_):
                self.controller.register_write("B{}".format(j), i, max_val)
                self.controller.register_write("T{}".format(j), i, 0)

    def set_crc_custom_hashes(self):
        i = 0
        for custom_crc32, width in sorted(self.custom_calcs.items()):
            self.controller.set_crc32_parameters(custom_crc32, crc32_polinomials[i], 0xffffffff, 0xffffffff, True, True)
            i+=1

    def create_hashes(self):
        self.hashes = []
        for i in range(self.register_num):
            self.hashes.append(Crc(32, crc32_polinomials[i], True, 0xffffffff, True, 0xffffffff))

    def read_registers(self):
        self.registers = []
        for i in range(1, self.register_num):
            self.registers.append(self.controller.register_read("B{}".format(i)))
        self.registers.append(self.controller.register_read("G"))

    def get_card(self):
        est = 0.0
        for j in range(len(self.registers[0])):
            sub_est = 0.0
            for i in range(self.register_num - 1):
                if self.registers[i][j] != max_val:
                    sub_est += 1
            sub_est = sub_est * (max_val / (1.0 * self.registers[self.register_num - 1][j]))
            est += sub_est
        return est

    def show_sketch(self):
        for i in range(len(self.registers[0])):
            print "B1[{}]={},B2[{}]={},B3[{}]={},G[{}]={}.".format(i, self.registers[0][i], i, self.registers[1][i], i, self.registers[2][i], i, self.registers[3][i])

    def get_relative_error(self, ground_truth_file="sent_flows.pickle"):

        """In the decoding function you were free to compute whatever you wanted.
           This solution includes a very basic statistic, with the number of flows inside the confidence bound.
        """
        self.read_registers()
        flows = pickle.load(open(ground_truth_file, "r"))
        real_diff_flows = set([])
        for flow, n_packets in flows.items():
            if n_packets != 0:
                real_diff_flows.add(flow[0])
        real_card = len(real_diff_flows)
        est_card = self.get_card()
        print abs(real_card - est_card) / (1.0 * real_card)
        return est_card, real_card, abs(real_card - est_card) / real_card

if __name__ == "__main__":

    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('--sw', help="switch name to configure" , type=str, required=False, default="s1")
    parser.add_argument('--flow-file', help="name of the file generated by send.py", type=str, required=False, default="sent_flows.pickle")
    parser.add_argument('--option', help="controller option can be either set_hashes, decode or reset registers", type=str, required=False, default="set_hashes")
    args = parser.parse_args()

    set_hashes = args.option == "set_hashes"
    controller = EController(args.sw, set_hashes)

    if args.option == "card":
        est, real, err = controller.get_relative_error(args.flow_file)
        print "real cardinality is {}".format(real)
        print "estimated cardinality is {}".format(est)
        controller.show_sketch()

    elif args.option == "reset":
        controller.reset_registers()
